<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Automation Test university testing" duration-ms="91690" started-at="2020-07-02T19:56:01Z" finished-at="2020-07-02T19:57:33Z">
    <groups>
    </groups>
    <test name="Automation Test university Test Cases" duration-ms="91690" started-at="2020-07-02T19:56:01Z" finished-at="2020-07-02T19:57:33Z">
      <class name="pageTests.HomePageTest">
        <test-method status="PASS" signature="Setup()" name="Setup" is-config="true" duration-ms="26483" started-at="2020-07-02T19:56:01Z" finished-at="2020-07-02T19:56:28Z">
        </test-method>
        <test-method status="PASS" signature="TestDrobdownLink()" name="TestDrobdownLink" duration-ms="668" started-at="2020-07-02T19:56:28Z" finished-at="2020-07-02T19:56:28Z">
        </test-method>
        <test-method status="PASS" signature="quit()" name="quit" is-config="true" duration-ms="4074" started-at="2020-07-02T19:56:28Z" finished-at="2020-07-02T19:56:32Z">
        </test-method>
        <test-method status="PASS" signature="Setup()" name="Setup" is-config="true" duration-ms="25830" started-at="2020-07-02T19:56:32Z" finished-at="2020-07-02T19:56:58Z">
        </test-method>
        <test-method status="FAIL" signature="TestHome()" name="TestHome" duration-ms="34" started-at="2020-07-02T19:56:58Z" finished-at="2020-07-02T19:56:58Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...> but was:<The...>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...> but was:<The...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at pageTests.HomePageTest.TestHome(HomePageTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="quit()" name="quit" is-config="true" duration-ms="3657" started-at="2020-07-02T19:56:58Z" finished-at="2020-07-02T19:57:02Z">
        </test-method>
        <test-method status="PASS" signature="Setup()" name="Setup" is-config="true" duration-ms="24184" started-at="2020-07-02T19:57:02Z" finished-at="2020-07-02T19:57:26Z">
        </test-method>
        <test-method status="FAIL" signature="TestHome()" name="TestHome" duration-ms="38" started-at="2020-07-02T19:57:26Z" finished-at="2020-07-02T19:57:26Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...> but was:<The...>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...> but was:<The...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at pageTests.HomePageTest.TestHome(HomePageTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:990)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="quit()" name="quit" is-config="true" duration-ms="6264" started-at="2020-07-02T19:57:27Z" finished-at="2020-07-02T19:57:33Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
